### ISSUE TITLE
Add backlink, remove placeholder

### ISSUE THREAD

**Issue by rgeirhos** [distillpub/post--ilyas-responses#2]
In https://distill.pub/2019/advex-bugs-discussion/response-6/ at the bottom of the page, the section "Backlink" looks like it's still under construction; it currently has the following placeholder text: "Probablhy [sic] will go here? Maybe also on top?".

**Comment by ludwigschubert** [comment]
Thanks for catching that, @rgeirhos !

(Fixed in sister repo, deploying by EOD)

**Comment by rgeirhos** [comment]
Also on the same page at the bottom, the links to github ("create an issue" / "source available on github") lead to a 404 error.

**Comment by ludwigschubert** [comment]
(That link also works now; the repo just wasn't public yet.)
